#!/bin/bash
set -e

# Deploy Infrastructure with Terraform to Floci
# This script initializes and applies Terraform configuration to LocalStack

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
TERRAFORM_DIR="$PROJECT_ROOT/terraform"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Logging functions
log_info() {
  echo -e "${GREEN}[INFO]${NC} $1"
}

log_error() {
  echo -e "${RED}[ERROR]${NC} $1"
  exit 1
}

log_warning() {
  echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_header() {
  echo ""
  echo -e "${BLUE}========================================${NC}"
  echo -e "${BLUE}$1${NC}"
  echo -e "${BLUE}========================================${NC}"
  echo ""
}

# Configuration
FLOCI_ENDPOINT="http://localhost:4566"
REGION="us-east-1"
ENVIRONMENT="prod"

# Main execution
log_header "TERRAFORM INFRASTRUCTURE DEPLOYMENT"

# Verify Floci is running
log_info "Verifying Floci is running..."
if ! curl -s "$FLOCI_ENDPOINT/_localstack/health" 2>/dev/null | grep -q '"state": "running"'; then
  log_error "Floci is not running. Start it with: bash scripts/setup-floci.sh"
fi
log_info "✓ Floci is running at $FLOCI_ENDPOINT"

# Set AWS credentials for Floci
export AWS_ACCESS_KEY_ID=test
export AWS_SECRET_ACCESS_KEY=test
export AWS_DEFAULT_REGION=$REGION
export AWS_ENDPOINT_URL=$FLOCI_ENDPOINT

log_info "✓ AWS credentials configured for Floci"

# Navigate to terraform directory
cd "$TERRAFORM_DIR"
log_info "Working directory: $(pwd)"

# Initialize Terraform
log_info "Initializing Terraform..."
if terraform init -upgrade 2>/dev/null; then
  log_info "✓ Terraform initialized"
else
  log_error "Terraform init failed"
fi

# Validate Terraform configuration
log_info "Validating Terraform configuration..."
if terraform validate 2>/dev/null; then
  log_info "✓ Terraform configuration is valid"
else
  log_error "Terraform validation failed"
fi

# Format check
log_info "Checking Terraform formatting..."
if terraform fmt -check -recursive 2>/dev/null; then
  log_info "✓ Terraform formatting is correct"
else
  log_warning "⚠ Terraform formatting issues detected (non-critical)"
fi

# Plan Terraform changes
log_info "Planning Terraform changes..."
terraform plan -var="aws_region=$REGION" -var="environment=$ENVIRONMENT" -out=tfplan 2>/dev/null || log_error "Terraform plan failed"
log_info "✓ Terraform plan generated"

# Apply Terraform changes
log_info "Applying Terraform changes..."
terraform apply -auto-approve tfplan 2>/dev/null || log_error "Terraform apply failed"
log_info "✓ Infrastructure deployed with Terraform"

# Extract and save outputs
log_info "Extracting Terraform outputs..."
ENV_FILE="$PROJECT_ROOT/.env.terraform"

# Get outputs in JSON format
OUTPUTS=$(terraform output -json 2>/dev/null || echo "{}")

# Extract individual outputs
API_ENDPOINT=$(echo "$OUTPUTS" | grep -o '"api_endpoint".*"value":"[^"]*"' | head -1 | grep -o '"value":"[^"]*"' | cut -d'"' -f4)
USER_POOL_ID=$(echo "$OUTPUTS" | grep -o '"user_pool_id".*"value":"[^"]*"' | head -1 | grep -o '"value":"[^"]*"' | cut -d'"' -f4)
USER_POOL_CLIENT_ID=$(echo "$OUTPUTS" | grep -o '"user_pool_client_id".*"value":"[^"]*"' | head -1 | grep -o '"value":"[^"]*"' | cut -d'"' -f4)
EVENTS_TABLE=$(echo "$OUTPUTS" | grep -o '"events_table_name".*"value":"[^"]*"' | head -1 | grep -o '"value":"[^"]*"' | cut -d'"' -f4)
BOOKINGS_TABLE=$(echo "$OUTPUTS" | grep -o '"bookings_table_name".*"value":"[^"]*"' | head -1 | grep -o '"value":"[^"]*"' | cut -d'"' -f4)
TICKETS_BUCKET=$(echo "$OUTPUTS" | grep -o '"tickets_bucket_name".*"value":"[^"]*"' | head -1 | grep -o '"value":"[^"]*"' | cut -d'"' -f4)
FRONTEND_BUCKET=$(echo "$OUTPUTS" | grep -o '"frontend_bucket_name".*"value":"[^"]*"' | head -1 | grep -o '"value":"[^"]*"' | cut -d'"' -f4)
BOOKING_QUEUE_URL=$(echo "$OUTPUTS" | grep -o '"booking_queue_url".*"value":"[^"]*"' | head -1 | grep -o '"value":"[^"]*"' | cut -d'"' -f4)

# Save outputs to environment file
log_info "Saving outputs to $ENV_FILE..."
cat > "$ENV_FILE" << EOF
# Terraform Stack Outputs
# Auto-generated by deploy-terraform.sh on $(date)

export FLOCI_ENDPOINT=$FLOCI_ENDPOINT
export REGION=$REGION
export ENVIRONMENT=$ENVIRONMENT

export API_ENDPOINT=$API_ENDPOINT
export USER_POOL_ID=$USER_POOL_ID
export USER_POOL_CLIENT_ID=$USER_POOL_CLIENT_ID
export EVENTS_TABLE=$EVENTS_TABLE
export BOOKINGS_TABLE=$BOOKINGS_TABLE
export TICKETS_BUCKET=$TICKETS_BUCKET
export FRONTEND_BUCKET=$FRONTEND_BUCKET
export BOOKING_QUEUE_URL=$BOOKING_QUEUE_URL

# For React Frontend
export REACT_APP_API_ENDPOINT=$API_ENDPOINT
export REACT_APP_COGNITO_USER_POOL_ID=$USER_POOL_ID
export REACT_APP_COGNITO_CLIENT_ID=$USER_POOL_CLIENT_ID
export REACT_APP_COGNITO_REGION=$REGION
export REACT_APP_DEBUG=false
EOF

log_info "✓ Outputs saved to .env.terraform"

# Display outputs
log_header "TERRAFORM OUTPUTS"

echo "API Endpoint:           $API_ENDPOINT"
echo "User Pool ID:           $USER_POOL_ID"
echo "User Pool Client ID:    $USER_POOL_CLIENT_ID"
echo "Events Table:           $EVENTS_TABLE"
echo "Bookings Table:         $BOOKINGS_TABLE"
echo "Tickets S3 Bucket:      $TICKETS_BUCKET"
echo "Frontend S3 Bucket:     $FRONTEND_BUCKET"
echo "Booking Queue URL:      $BOOKING_QUEUE_URL"
echo ""

# List all resources
log_info "Listing Terraform resources..."
terraform state list

# Next steps
log_header "DEPLOYMENT COMPLETE"

echo "Terraform infrastructure deployed successfully!"
echo ""
echo "Environment outputs saved to: $ENV_FILE"
echo "Load them with: source $ENV_FILE"
echo ""
echo "Next steps:"
echo "  1. Seed data:           bash scripts/seed-data.sh"
echo "  2. Build frontend:      bash scripts/build-frontend.sh"
echo "  3. Deploy frontend:     bash scripts/deploy-frontend.sh"
echo "  4. Start frontend:      npm start (from frontend/)"
echo ""
echo "Or run full pipeline:"
echo "  bash scripts/full-pipeline.sh"
echo ""
echo "To view Floci logs:"
echo "  podman-compose logs -f floci"
echo ""
echo "To clean up:"
echo "  bash scripts/cleanup.sh"
echo ""

log_info "Terraform deployment complete!"
